#!/bin/sh
#
# @name Gazebo x500 gimbal
# 
# @type Quadrotor
#
# https://discuss.px4.io/t/raising-landing-legs-on-a-drone/32816/3

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_gimbal}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203